package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./{{ name }}-{{ version }}-{{ python }}_{{ build_number }}.tar.gz

build:
  number: "{{ build_number }}"

requirements:
  host:
    - python
  run:
    - python
    - qt

about:
  home: https://github.com/flaport/condalayout/
  license: GPLv3
  summary: Conda + KLayout
  description: Conda + KLayout
  dev_url: https://github.com/flaport/condalayout/
  doc_url: https://github.com/flaport/condalayout/
  doc_source_url: https://github.com/flaport/condalayout/
