{% set name = "klayout-gui" %}
{% set version = "0.27.8" %}
{% set python = "py38" %}
{% set build_number = "0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./{{ name }}-{{ version }}-{{ python }}_{{ build_number }}.tar.gz

build:
  number: {{ build_number }}

requirements:
  host:
    - python
  run:
    - python
    - qt

about:
  home: https://github.com/flaport/condalayout/
  license: Apache2
  summary: Conda + KLayout
  description: Conda + KLayout
  dev_url: https://github.com/flaport/condalayout/
  doc_url: https://github.com/flaport/condalayout/
  doc_source_url: https://github.com/flaport/condalayout/
