name: docker
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --no-cache -t flaport/condalayout:latest --build-arg WORKERS=2 --build-arg PYTHON_VERSION=3.8 --build-arg KLAYOUT_VERSION=0.27.8
    - name: Push the tagged Docker image
      run: docker push flaport/condalayout:latest
