name: main
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]'

jobs:

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: build or pull docker image using git tag
        run: |
          if ! docker pull flaport/condalayout:${{ github.ref_name}} > /dev/null 2> /dev/null; then
            docker build . -t flaport/condalayout:${{ github.ref_name }} --build-arg WORKERS=2 --build-arg PYTHON_VERSION=3.8 --build-arg KLAYOUT_VERSION=${{ github.ref_name }};
          fi
      - name: tag docker image as latest
        run: docker tag flaport/condalayout:${{ github.ref_name }} flaport/condalayout:latest
      - name: push docker image
        run: docker push flaport/condalayout:latest && docker push flaport/condalayout:${{ github.ref_name }}

  release:
    runs-on: ubuntu-latest
    needs:
      - docker
    container:
      image: flaport/condalayout
    steps:
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          prerelease: true
          release_name: klayout v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
      - name: add tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /klayout/klayout.tar.gz
          asset_name: klayout.tar.gz
          asset_content_type: application/gzip

