name: main
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]'


env:
  WORKERS: 2
  PYTHON_SEMVER: 3.8
  BUILD_NUMBER: 0
  KLAYOUT_SEMVER: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: build or pull docker image using git tag
        run: ./build-docker.sh

  release:
    runs-on: ubuntu-latest
    needs:
      - docker
    container:
      image: flaport/condalayout
    steps:
      - name: create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: KLayout v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
      - name: klayout-gui - add gzip tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /klayout/dist/klayout-gui-0.27.8-py38_0.tar.gz
          asset_name: klayout-gui-0.27.8-py38_0.tar.gz
          asset_content_type: application/x-gzip
      - name: klayout-gui - add bzip tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /klayout/dist/klayout-gui-0.27.8-py38_0.tar.bz2
          asset_name: klayout-gui-0.27.8-py38_0.tar.bz2
          asset_content_type: application/x-bzip2
      - name: klayout - add bzip tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /klayout/dist/klayout-0.27.8-py38_0.tar.bz2
          asset_name: klayout-0.27.8-py38_0.tar.bz2
          asset_content_type: application/x-bzip2
      - name: login to anaconda.org
        run: anaconda login --username '${{ secrets.ANACONDA_USER }}' --password '${{ secrets.ANACONDA_PASSWORD }}'
      - name: klayout-gui - upload to anaconda.org
        run: anaconda upload /klayout/dist/klayout-gui-0.27.8-py38_0.tar.bz2
      - name: klayout - upload to anaconda.org
        run: anaconda upload /klayout/dist/klayout-0.27.8-py38_0.tar.bz2
