name: release
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]'

jobs:
  release:
    runs-on: ubuntu-latest
    needs:
      - docker
    container:
      image: flaport/condalayout
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Expose 'klayout.tar.gz' as artifact
        uses: actions/upload-artifact@master
        with:
          name: nbdev_test_nbs.log
          path: /klayout/klayout.tar.gz
